### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by danperks** [supabase-community/pg_paper_dump#1]
# Feature request

## Is your feature request related to a problem? Please describe.

The documentation currently only supports Windows (and some Linux text processors by default) with the suggestion of using CTRL+P to export the database dump.

## Describe the solution you'd like

Ideally, this functionality would be extended to support all platforms, including MacOS.

## Describe alternatives you've considered

The Supabase CLI could be updated to trigger the CTRL+P (and cross platform equivalents) as part of the process, avoiding the need for the user to know and trigger the shortcut themselves.

## Additional context

I would offer up a pull request with a fix for this, but I believe it's likely too complex for my skill level and would likely require a large amount of Supabase resource to ensure completely aligned functionality across all the platforms.

**Comment by dshukertjr** [comment]
Great idea! Would you like to work on a PR for it?

**Comment by danperks** [comment]
While the issue sounds trivial, I believe this would require significant work and discussion within the Supabase team and its community to get even the simplest of solutions up and running!

**Comment by danperks** [comment]
Scrap that, just dropped a pull request to add it in :)

**Comment by loong** [comment]
Porting libraries across platforms is extremely hard. Thank you @danperks

**Comment by danperks** [comment]
@loong If Supabase ever needs some cross-platform engineers, you know where to find me 😉
